#!/bin/bash

# Neovim keybindings menu for rofi
# Shows useful nvim keybindings and commands

KEYBINDS=(
    "Space + e • Toggle file tree sidebar (neo-tree)"
    "Space + ff • Find files (Telescope)"
    "Space + fg • Find by grep (Telescope)"
    "Space + fb • Find buffers (Telescope)"
    "Space + fh • Find help (Telescope)"
    "Space + fd • Find diagnostics (Telescope)"
    "Space + fs • Find symbols in file (Telescope)"
    "Space + fw • Find symbols in workspace (Telescope)"
    "Space + fm • Find macros (#define)"
    "Space + mp • Markdown preview (toggle)"
    "Space + q • Show all diagnostics (full text)"
    "Space + d • Show diagnostic at cursor"
    "---"
    "Ctrl + h/j/k/l • Navigate between windows"
    "Ctrl + w + v • Split window vertically"
    "Ctrl + w + s • Split window horizontally"
    "Ctrl + w + q • Close current window"
    "---"
    "gd • Go to definition (LSP)"
    "gD • Go to declaration (LSP)"
    "gr • Go to references (LSP)"
    "gI • Go to implementation (LSP)"
    "K • Show hover documentation (LSP)"
    "Space + h • Switch header/source (C++)"
    "Space + rn • Rename symbol (LSP)"
    "Space + ca • Code actions (LSP + Generate definition)"
    "Space + cf • Batch fix with clang-tidy (C++)"
    "Space + F • Format code (clang-format)"
    "Space + D • Type definition (LSP)"
    "---"
    "TIPS: Space+q then Enter to jump to diagnostic"
    "TIPS: Space+ca on function declaration = generate impl"
    "TIPS: ]d / [d to jump next/previous diagnostic"
    "---"
    "Space + gb • Toggle git blame"
    "Space + hb • Show blame for current line"
    "Space + hp • Preview git hunk"
    "Space + hs • Stage hunk"
    "Space + hr • Reset hunk (undo changes)"
    "Space + hd • Show diff"
    "]c / [c • Next/previous git hunk"
    "---"
    "F5 • Start/Continue debugging"
    "F10 • Step over"
    "F11 • Step into"
    "F12 • Step out"
    "Space + b • Toggle breakpoint"
    "Space + B • Conditional breakpoint"
    "Space + du • Toggle debug UI"
    "---"
    ":w • Save file"
    ":q • Quit"
    ":wq • Save and quit"
    ":q! • Quit without saving"
    "---"
    "i • Enter insert mode"
    "v • Enter visual mode"
    "Esc • Return to normal mode"
    "u • Undo"
    "Ctrl + r • Redo"
    "---"
    "dd • Delete line"
    "yy • Yank (copy) line"
    "p • Paste"
    "/ • Search"
    "n • Next search result"
    "N • Previous search result"
    ":%s/old/new/g • Replace all"
    "---"
    "=== NAVIGATION ==="
    "---"
    "Ctrl + d • Half page DOWN (smooth scroll)"
    "Ctrl + u • Half page UP (smooth scroll)"
    "zz • Center current line on screen"
    "zt • Current line to TOP"
    "zb • Current line to BOTTOM"
    "H / M / L • Jump to High/Middle/Low of screen"
    "{ / } • Jump by paragraph/block"
    "---"
    "gg • Go to top of file"
    "G • Go to bottom of file"
    "50% • Jump to 50% of file"
    ":100 • Jump to line 100"
    "0 • Go to start of line"
    "^ • First non-blank character"
    "$ • Go to end of line"
    "---"
    "w / W • Next word / WORD"
    "b / B • Back word / WORD"
    "e • End of word"
    "f<char> • Find char forward (e.g., f( )"
    "F<char> • Find char backward"
    "; • Repeat last f/F/t/T"
    "---"
    "* • Search word under cursor (forward)"
    "# • Search word under cursor (backward)"
    "% • Jump to matching bracket"
    "[[ / ]] • Previous/next function"
    "[{ / ]} • Jump to opening/closing { of block"
    "---"
    "Ctrl + o • Jump BACK (older position)"
    "Ctrl + i • Jump FORWARD (newer position)"
    "'' • Jump to last position"
    "'. • Jump to last edit location"
    "---"
    "ma • Set mark 'a'"
    "'a • Jump to mark 'a'"
    "---"
    ":bn / :bp • Next/previous buffer"
    "Ctrl + 6 • Toggle last two buffers"
    ":bd • Close buffer"
)

# Join array with newlines
MENU=$(printf '%s\n' "${KEYBINDS[@]}")

# Show menu in rofi
SELECTED=$(echo "$MENU" | rofi -dmenu -i -p "Neovim Keybindings" -theme-str 'window {width: 55%;}' -theme-str 'listview {lines: 20;}')

# If something was selected, copy the keybind part to clipboard
if [ -n "$SELECTED" ]; then
    # Skip separator lines
    if [ "$SELECTED" != "---" ]; then
        # Extract just the keybind (before the •)
        KEYBIND=$(echo "$SELECTED" | sed 's/ •.*//')
        echo -n "$KEYBIND" | wl-copy
        notify-send "Keybind Copied" "$KEYBIND" -t 2000
    fi
fi
